
import __ASTRO_IMAGE_IMPORT_1z2s8g from "../../assets/blog-wallets-with-timelock.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-4.md";
import __ASTRO_IMAGE_IMPORT_136NGe from "../../assets/blog-placeholder-about.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-2.md";
import __ASTRO_IMAGE_IMPORT_28CQOO from "../../assets/blog-btc-node.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-2.md";
import __ASTRO_IMAGE_IMPORT_Z70Qf7 from "../../assets/blog-inheritance.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-5.md";
import __ASTRO_IMAGE_IMPORT_1FXhYF from "../../assets/blog-privacy.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-3.md";
import __ASTRO_IMAGE_IMPORT_Z70Aem from "../../assets/blog-inheritance.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-7.md";
import __ASTRO_IMAGE_IMPORT_Z14SLEP from "../../assets/blog-bitcoin-file-store-protocol.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-10.md";
import __ASTRO_IMAGE_IMPORT_ZtIC8t from "../../assets/blog-multisig.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuying-bitcoin-is-easy-custody-is-the-problem-exchange-to-multisig.md";
import __ASTRO_IMAGE_IMPORT_3B3XF from "../../assets/blog-price-light.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-9.md";
import __ASTRO_IMAGE_IMPORT_avhPn from "../../assets/blog-block-clock.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-8.md";
import __ASTRO_IMAGE_IMPORT_1k1l2w from "../../assets/blog-buy-borrow-die.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-6.md";
import __ASTRO_IMAGE_IMPORT_Z2u5Eoy from "../../assets/blog-bitcoin-file-store-protocol.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fsecond-project.md";
import __ASTRO_IMAGE_IMPORT_Z17fsH8 from "../../assets/blog-placeholder-about.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ffirst-project.md";
export default new Map([["../../assets/blog-wallets-with-timelock.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-4.md", __ASTRO_IMAGE_IMPORT_1z2s8g], ["../../assets/blog-placeholder-about.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-2.md", __ASTRO_IMAGE_IMPORT_136NGe], ["../../assets/blog-btc-node.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-2.md", __ASTRO_IMAGE_IMPORT_28CQOO], ["../../assets/blog-inheritance.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-5.md", __ASTRO_IMAGE_IMPORT_Z70Qf7], ["../../assets/blog-privacy.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-3.md", __ASTRO_IMAGE_IMPORT_1FXhYF], ["../../assets/blog-inheritance.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-7.md", __ASTRO_IMAGE_IMPORT_Z70Aem], ["../../assets/blog-bitcoin-file-store-protocol.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-10.md", __ASTRO_IMAGE_IMPORT_Z14SLEP], ["../../assets/blog-multisig.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuying-bitcoin-is-easy-custody-is-the-problem-exchange-to-multisig.md", __ASTRO_IMAGE_IMPORT_ZtIC8t], ["../../assets/blog-price-light.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-9.md", __ASTRO_IMAGE_IMPORT_3B3XF], ["../../assets/blog-block-clock.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-8.md", __ASTRO_IMAGE_IMPORT_avhPn], ["../../assets/blog-buy-borrow-die.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Farticle-6.md", __ASTRO_IMAGE_IMPORT_1k1l2w], ["../../assets/blog-bitcoin-file-store-protocol.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fsecond-project.md", __ASTRO_IMAGE_IMPORT_Z2u5Eoy], ["../../assets/blog-placeholder-about.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Ffirst-project.md", __ASTRO_IMAGE_IMPORT_Z17fsH8]]);
		