author:
  name: Miro Remias
  role: Problem Solver
  bio: Discover, understand and find solution. Freedom believer. Bitcoiner. Happy father. Long distance runner. World traveler.
  location: Switzerland, Europe

social:
  - id: "website"
    label: "Web site"
    href: "https://miro.foremsec.com/"
  - id: "x"
    label: "X"
    href: "https://x.com/mr21free"
  - id: "github"
    label: "GitHub"
    href: "https://github.com/mr21free"
  - id: "linkedin"
    label: "Linkedin"
    href: "https://www.linkedin.com/in/miroremias/"
  - id: "telegram"
    label: "Telegram"
    href: "https://t.me/mr21free"
  - id: "discord"
    label: "Discord"
    href: "https://discord.com/users/1477780392638681262"
  - id: "email"
    label: "Email"
    href: "mailto:miro.remias@foremsec.com"

contact:
  vcardPath: "/miro-remias-contact.vcf"
